/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

/**
 *
 * @author Prateet
 */
public class Answer extends javax.swing.JFrame {

    //int[][] b;
    /**
     * Creates new form Answer
     */
    public Answer(int[][] b) {
        initComponents();
        
        /*b = new int[][]{{3, 0, 6, 5, 0, 8, 4, 0, 0},
                        {5, 2, 0, 0, 0, 0, 0, 0, 0},
                        {0, 8, 7, 0, 0, 0, 0, 3, 1},
                        {0, 0, 3, 0, 1, 0, 0, 8, 0},
                        {9, 0, 0, 8, 6, 3, 0, 0, 5},
                        {0, 5, 0, 0, 9, 0, 6, 0, 0},
                        {1, 3, 0, 0, 0, 0, 2, 5, 0},
                        {0, 0, 0, 0, 0, 0, 0, 7, 4},
                        {0, 0, 5, 2, 0, 6, 3, 0, 0}};*/
        
        j1.setText(""+b[1-1][1-1]);
        j2.setText(""+b[1-1][2-1]);
        j3.setText(""+b[1-1][3-1]);
        j4.setText(""+b[1-1][4-1]);
        j5.setText(""+b[1-1][5-1]);
        j6.setText(""+b[1-1][6-1]);
        j7.setText(""+b[1-1][7-1]);
        j8.setText(""+b[1-1][8-1]);
        j9.setText(""+b[1-1][9-1]);
        j10.setText(""+b[2-1][1-1]);
        j11.setText(""+b[2-1][2-1]);
        j12.setText(""+b[2-1][3-1]);
        j13.setText(""+b[2-1][4-1]);
        j14.setText(""+b[2-1][5-1]);
        j15.setText(""+b[2-1][6-1]);
        j16.setText(""+b[2-1][7-1]);
        j17.setText(""+b[2-1][8-1]);
        j18.setText(""+b[2-1][9-1]);
        j19.setText(""+b[3-1][1-1]);
        j20.setText(""+b[3-1][2-1]);
        j21.setText(""+b[3-1][3-1]);
        j22.setText(""+b[3-1][4-1]);
        j23.setText(""+b[3-1][5-1]);
        j24.setText(""+b[3-1][6-1]);
        j25.setText(""+b[3-1][7-1]);
        j26.setText(""+b[3-1][8-1]);
        j27.setText(""+b[3-1][9-1]);
        j28.setText(""+b[4-1][1-1]);
        j29.setText(""+b[4-1][2-1]);
        j30.setText(""+b[4-1][3-1]);
        j31.setText(""+b[4-1][4-1]);
        j32.setText(""+b[4-1][5-1]);
        j33.setText(""+b[4-1][6-1]);
        j34.setText(""+b[4-1][7-1]);
        j35.setText(""+b[4-1][8-1]);
        j36.setText(""+b[4-1][9-1]);
        j37.setText(""+b[5-1][1-1]);
        j38.setText(""+b[5-1][2-1]);
        j39.setText(""+b[5-1][3-1]);
        j40.setText(""+b[5-1][4-1]);
        j41.setText(""+b[5-1][5-1]);
        j42.setText(""+b[5-1][6-1]);
        j43.setText(""+b[5-1][7-1]);
        j44.setText(""+b[5-1][8-1]);
        j45.setText(""+b[5-1][9-1]);
        j46.setText(""+b[6-1][1-1]);
        j47.setText(""+b[6-1][2-1]);
        j48.setText(""+b[6-1][3-1]);
        j49.setText(""+b[6-1][4-1]);
        j50.setText(""+b[6-1][5-1]);
        j51.setText(""+b[6-1][6-1]);
        j52.setText(""+b[6-1][7-1]);
        j53.setText(""+b[6-1][8-1]);
        j54.setText(""+b[6-1][9-1]);
        j55.setText(""+b[7-1][1-1]);
        j56.setText(""+b[7-1][2-1]);
        j57.setText(""+b[7-1][3-1]);
        j58.setText(""+b[7-1][4-1]);
        j59.setText(""+b[7-1][5-1]);
        j60.setText(""+b[7-1][6-1]);
        j61.setText(""+b[7-1][7-1]);
        j62.setText(""+b[7-1][8-1]);
        j63.setText(""+b[7-1][9-1]);
        j64.setText(""+b[8-1][1-1]);
        j65.setText(""+b[8-1][2-1]);
        j66.setText(""+b[8-1][3-1]);
        j67.setText(""+b[8-1][4-1]);
        j68.setText(""+b[8-1][5-1]);
        j69.setText(""+b[8-1][6-1]);
        j70.setText(""+b[8-1][7-1]);
        j71.setText(""+b[8-1][8-1]);
        j72.setText(""+b[8-1][9-1]);
        j73.setText(""+b[9-1][1-1]);
        j74.setText(""+b[9-1][2-1]);
        j75.setText(""+b[9-1][3-1]);
        j76.setText(""+b[9-1][4-1]);
        j77.setText(""+b[9-1][5-1]);
        j78.setText(""+b[9-1][6-1]);
        j79.setText(""+b[9-1][7-1]);
        j80.setText(""+b[9-1][8-1]);
        j81.setText(""+b[9-1][9-1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j9 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j19 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j25 = new javax.swing.JTextField();
        j26 = new javax.swing.JTextField();
        j27 = new javax.swing.JTextField();
        j28 = new javax.swing.JTextField();
        j29 = new javax.swing.JTextField();
        j30 = new javax.swing.JTextField();
        j31 = new javax.swing.JTextField();
        j32 = new javax.swing.JTextField();
        j33 = new javax.swing.JTextField();
        j34 = new javax.swing.JTextField();
        j35 = new javax.swing.JTextField();
        j36 = new javax.swing.JTextField();
        j37 = new javax.swing.JTextField();
        j38 = new javax.swing.JTextField();
        j39 = new javax.swing.JTextField();
        j40 = new javax.swing.JTextField();
        j41 = new javax.swing.JTextField();
        j42 = new javax.swing.JTextField();
        j43 = new javax.swing.JTextField();
        j44 = new javax.swing.JTextField();
        j45 = new javax.swing.JTextField();
        j46 = new javax.swing.JTextField();
        j47 = new javax.swing.JTextField();
        j48 = new javax.swing.JTextField();
        j49 = new javax.swing.JTextField();
        j50 = new javax.swing.JTextField();
        j51 = new javax.swing.JTextField();
        j52 = new javax.swing.JTextField();
        j53 = new javax.swing.JTextField();
        j54 = new javax.swing.JTextField();
        j55 = new javax.swing.JTextField();
        j56 = new javax.swing.JTextField();
        j57 = new javax.swing.JTextField();
        j58 = new javax.swing.JTextField();
        j59 = new javax.swing.JTextField();
        j60 = new javax.swing.JTextField();
        j61 = new javax.swing.JTextField();
        j62 = new javax.swing.JTextField();
        j63 = new javax.swing.JTextField();
        j64 = new javax.swing.JTextField();
        j65 = new javax.swing.JTextField();
        j66 = new javax.swing.JTextField();
        j67 = new javax.swing.JTextField();
        j68 = new javax.swing.JTextField();
        j69 = new javax.swing.JTextField();
        j70 = new javax.swing.JTextField();
        j71 = new javax.swing.JTextField();
        j72 = new javax.swing.JTextField();
        j73 = new javax.swing.JTextField();
        j74 = new javax.swing.JTextField();
        j75 = new javax.swing.JTextField();
        j76 = new javax.swing.JTextField();
        j77 = new javax.swing.JTextField();
        j78 = new javax.swing.JTextField();
        j79 = new javax.swing.JTextField();
        j80 = new javax.swing.JTextField();
        j81 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1.setText("0");

        j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2.setText("0");

        j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j3.setText("0");

        j4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j4.setText("0");

        j5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j5.setText("0");

        j6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j6.setText("0");

        j7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j7.setText("0");

        j8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j8.setText("0");

        j9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j9.setText("0");

        j10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j10.setText("0");

        j11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j11.setText("0");

        j12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j12.setText("0");

        j13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j13.setText("0");

        j14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j14.setText("0");

        j15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j15.setText("0");

        j16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j16.setText("0");

        j17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j17.setText("0");

        j18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j18.setText("0");

        j19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j19.setText("0");

        j20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j20.setText("0");

        j21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j21.setText("0");

        j22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j22.setText("0");

        j23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j23.setText("0");

        j24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j24.setText("0");

        j25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j25.setText("0");

        j26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j26.setText("0");

        j27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j27.setText("0");

        j28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j28.setText("0");

        j29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j29.setText("0");

        j30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j30.setText("0");

        j31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j31.setText("0");

        j32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j32.setText("0");

        j33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j33.setText("0");

        j34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j34.setText("0");

        j35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j35.setText("0");

        j36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j36.setText("0");

        j37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j37.setText("0");

        j38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j38.setText("0");

        j39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j39.setText("0");

        j40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j40.setText("0");

        j41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j41.setText("0");

        j42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j42.setText("0");

        j43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j43.setText("0");

        j44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j44.setText("0");

        j45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j45.setText("0");

        j46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j46.setText("0");

        j47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j47.setText("0");

        j48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j48.setText("0");

        j49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j49.setText("0");

        j50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j50.setText("0");

        j51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j51.setText("0");

        j52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j52.setText("0");

        j53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j53.setText("0");

        j54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j54.setText("0");

        j55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j55.setText("0");

        j56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j56.setText("0");

        j57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j57.setText("0");

        j58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j58.setText("0");

        j59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j59.setText("0");

        j60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j60.setText("0");

        j61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j61.setText("0");

        j62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j62.setText("0");

        j63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j63.setText("0");

        j64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j64.setText("0");

        j65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j65.setText("0");

        j66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j66.setText("0");

        j67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j67.setText("0");

        j68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j68.setText("0");

        j69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j69.setText("0");

        j70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j70.setText("0");

        j71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j71.setText("0");

        j72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j72.setText("0");

        j73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j73.setText("0");

        j74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j74.setText("0");

        j75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j75.setText("0");

        j76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j76.setText("0");

        j77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j77.setText("0");
        j77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j77ActionPerformed(evt);
            }
        });

        j78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j78.setText("0");

        j79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j79.setText("0");

        j80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j80.setText("0");

        j81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j81.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ANSWER ->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j69, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(j79, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j69, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j79, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j77ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Answer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j19;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j25;
    private javax.swing.JTextField j26;
    private javax.swing.JTextField j27;
    private javax.swing.JTextField j28;
    private javax.swing.JTextField j29;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j30;
    private javax.swing.JTextField j31;
    private javax.swing.JTextField j32;
    private javax.swing.JTextField j33;
    private javax.swing.JTextField j34;
    private javax.swing.JTextField j35;
    private javax.swing.JTextField j36;
    private javax.swing.JTextField j37;
    private javax.swing.JTextField j38;
    private javax.swing.JTextField j39;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j40;
    private javax.swing.JTextField j41;
    private javax.swing.JTextField j42;
    private javax.swing.JTextField j43;
    private javax.swing.JTextField j44;
    private javax.swing.JTextField j45;
    private javax.swing.JTextField j46;
    private javax.swing.JTextField j47;
    private javax.swing.JTextField j48;
    private javax.swing.JTextField j49;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j50;
    private javax.swing.JTextField j51;
    private javax.swing.JTextField j52;
    private javax.swing.JTextField j53;
    private javax.swing.JTextField j54;
    private javax.swing.JTextField j55;
    private javax.swing.JTextField j56;
    private javax.swing.JTextField j57;
    private javax.swing.JTextField j58;
    private javax.swing.JTextField j59;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j60;
    private javax.swing.JTextField j61;
    private javax.swing.JTextField j62;
    private javax.swing.JTextField j63;
    private javax.swing.JTextField j64;
    private javax.swing.JTextField j65;
    private javax.swing.JTextField j66;
    private javax.swing.JTextField j67;
    private javax.swing.JTextField j68;
    private javax.swing.JTextField j69;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j70;
    private javax.swing.JTextField j71;
    private javax.swing.JTextField j72;
    private javax.swing.JTextField j73;
    private javax.swing.JTextField j74;
    private javax.swing.JTextField j75;
    private javax.swing.JTextField j76;
    private javax.swing.JTextField j77;
    private javax.swing.JTextField j78;
    private javax.swing.JTextField j79;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j80;
    private javax.swing.JTextField j81;
    private javax.swing.JTextField j9;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
