/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Prateet
 */
public class Start extends javax.swing.JFrame {

    int[][] c=new int[9][9];
    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        //jTable1.setTableHeader(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j19 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j25 = new javax.swing.JTextField();
        j26 = new javax.swing.JTextField();
        j27 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j9 = new javax.swing.JTextField();
        j28 = new javax.swing.JTextField();
        j29 = new javax.swing.JTextField();
        j30 = new javax.swing.JTextField();
        j31 = new javax.swing.JTextField();
        j32 = new javax.swing.JTextField();
        j33 = new javax.swing.JTextField();
        j34 = new javax.swing.JTextField();
        j35 = new javax.swing.JTextField();
        j36 = new javax.swing.JTextField();
        j37 = new javax.swing.JTextField();
        j38 = new javax.swing.JTextField();
        j39 = new javax.swing.JTextField();
        j40 = new javax.swing.JTextField();
        j41 = new javax.swing.JTextField();
        j42 = new javax.swing.JTextField();
        j43 = new javax.swing.JTextField();
        j44 = new javax.swing.JTextField();
        j45 = new javax.swing.JTextField();
        j46 = new javax.swing.JTextField();
        j47 = new javax.swing.JTextField();
        j48 = new javax.swing.JTextField();
        j49 = new javax.swing.JTextField();
        j50 = new javax.swing.JTextField();
        j51 = new javax.swing.JTextField();
        j52 = new javax.swing.JTextField();
        j53 = new javax.swing.JTextField();
        j54 = new javax.swing.JTextField();
        j55 = new javax.swing.JTextField();
        j56 = new javax.swing.JTextField();
        j57 = new javax.swing.JTextField();
        j58 = new javax.swing.JTextField();
        j59 = new javax.swing.JTextField();
        j60 = new javax.swing.JTextField();
        j61 = new javax.swing.JTextField();
        j62 = new javax.swing.JTextField();
        j63 = new javax.swing.JTextField();
        j64 = new javax.swing.JTextField();
        j65 = new javax.swing.JTextField();
        j66 = new javax.swing.JTextField();
        j67 = new javax.swing.JTextField();
        j68 = new javax.swing.JTextField();
        j69 = new javax.swing.JTextField();
        j70 = new javax.swing.JTextField();
        j71 = new javax.swing.JTextField();
        j72 = new javax.swing.JTextField();
        j73 = new javax.swing.JTextField();
        j74 = new javax.swing.JTextField();
        j75 = new javax.swing.JTextField();
        j76 = new javax.swing.JTextField();
        j77 = new javax.swing.JTextField();
        j78 = new javax.swing.JTextField();
        j79 = new javax.swing.JTextField();
        j80 = new javax.swing.JTextField();
        j81 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("SUDOKU SOLVER");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUDOKU SOLVER");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j20.setText("0");
        getContentPane().add(j20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 30, 30));

        j21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j21.setText("0");
        getContentPane().add(j21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 30, 30));

        j24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j24.setText("0");
        getContentPane().add(j24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 30, 30));

        j19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j19.setText("0");
        getContentPane().add(j19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 30, 30));

        j22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j22.setText("0");
        getContentPane().add(j22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 30, 30));

        j23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j23.setText("0");
        getContentPane().add(j23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 30, 30));

        j25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j25.setText("0");
        getContentPane().add(j25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 30, 30));

        j26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j26.setText("0");
        getContentPane().add(j26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 30, 30));

        j27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j27.setText("0");
        getContentPane().add(j27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 30, 30));

        j10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j10.setText("0");
        getContentPane().add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 30, 30));

        j11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j11.setText("0");
        getContentPane().add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 30, 30));

        j12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j12.setText("0");
        getContentPane().add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 30, 30));

        j13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j13.setText("0");
        getContentPane().add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 30, 30));

        j14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j14.setText("0");
        getContentPane().add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 30, 30));

        j15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j15.setText("0");
        getContentPane().add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 30, 30));

        j16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j16.setText("0");
        getContentPane().add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 30, 30));

        j17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j17.setText("0");
        getContentPane().add(j17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 30, 30));

        j18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j18.setText("0");
        getContentPane().add(j18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 30, 30));

        j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1.setText("0");
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 30, 30));

        j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2.setText("0");
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 30, 30));

        j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j3.setText("0");
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 30, 30));

        j4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j4.setText("0");
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 30, 30));

        j5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j5.setText("0");
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 30, 30));

        j6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j6.setText("0");
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 30, 30));

        j7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j7.setText("0");
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 30, 30));

        j8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j8.setText("0");
        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 30, 30));

        j9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j9.setText("0");
        getContentPane().add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 30, 30));

        j28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j28.setText("0");
        getContentPane().add(j28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 30, 30));

        j29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j29.setText("0");
        getContentPane().add(j29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 30, 30));

        j30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j30.setText("0");
        getContentPane().add(j30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 30, 30));

        j31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j31.setText("0");
        getContentPane().add(j31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 30, 30));

        j32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j32.setText("0");
        getContentPane().add(j32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 30, 30));

        j33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j33.setText("0");
        getContentPane().add(j33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 30, 30));

        j34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j34.setText("0");
        getContentPane().add(j34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, 30));

        j35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j35.setText("0");
        getContentPane().add(j35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 30, 30));

        j36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j36.setText("0");
        getContentPane().add(j36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 30, 30));

        j37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j37.setText("0");
        getContentPane().add(j37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 30, 30));

        j38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j38.setText("0");
        getContentPane().add(j38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 30, 30));

        j39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j39.setText("0");
        getContentPane().add(j39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 30, 30));

        j40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j40.setText("0");
        getContentPane().add(j40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 30, 30));

        j41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j41.setText("0");
        getContentPane().add(j41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 30, 30));

        j42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j42.setText("0");
        getContentPane().add(j42, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 30, 30));

        j43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j43.setText("0");
        getContentPane().add(j43, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, 30));

        j44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j44.setText("0");
        getContentPane().add(j44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 30, 30));

        j45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j45.setText("0");
        getContentPane().add(j45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 30, 30));

        j46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j46.setText("0");
        getContentPane().add(j46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 30, 30));

        j47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j47.setText("0");
        getContentPane().add(j47, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 30, 30));

        j48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j48.setText("0");
        getContentPane().add(j48, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 30, 30));

        j49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j49.setText("0");
        getContentPane().add(j49, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 30, 30));

        j50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j50.setText("0");
        getContentPane().add(j50, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 30, 30));

        j51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j51.setText("0");
        getContentPane().add(j51, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        j52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j52.setText("0");
        getContentPane().add(j52, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 30, 30));

        j53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j53.setText("0");
        getContentPane().add(j53, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 30, 30));

        j54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j54.setText("0");
        getContentPane().add(j54, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 30, 30));

        j55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j55.setText("0");
        getContentPane().add(j55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 30, 30));

        j56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j56.setText("0");
        getContentPane().add(j56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 30, 30));

        j57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j57.setText("0");
        getContentPane().add(j57, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 30, 30));

        j58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j58.setText("0");
        getContentPane().add(j58, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 30, 30));

        j59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j59.setText("0");
        getContentPane().add(j59, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 30, 30));

        j60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j60.setText("0");
        getContentPane().add(j60, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 30, 30));

        j61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j61.setText("0");
        getContentPane().add(j61, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 30, 30));

        j62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j62.setText("0");
        getContentPane().add(j62, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 30, 30));

        j63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j63.setText("0");
        getContentPane().add(j63, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 30, 30));

        j64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j64.setText("0");
        getContentPane().add(j64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 30, 30));

        j65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j65.setText("0");
        getContentPane().add(j65, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 30, 30));

        j66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j66.setText("0");
        getContentPane().add(j66, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 30, 30));

        j67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j67.setText("0");
        getContentPane().add(j67, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 30, 30));

        j68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j68.setText("0");
        getContentPane().add(j68, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 30, 30));

        j69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j69.setText("0");
        getContentPane().add(j69, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 30, 30));

        j70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j70.setText("0");
        getContentPane().add(j70, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 30, 30));

        j71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j71.setText("0");
        getContentPane().add(j71, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 30, 30));

        j72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j72.setText("0");
        getContentPane().add(j72, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 30, 30));

        j73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j73.setText("0");
        getContentPane().add(j73, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 30, 30));

        j74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j74.setText("0");
        getContentPane().add(j74, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 30, 30));

        j75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j75.setText("0");
        getContentPane().add(j75, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 30, 30));

        j76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j76.setText("0");
        getContentPane().add(j76, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 30, 30));

        j77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j77.setText("0");
        j77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j77ActionPerformed(evt);
            }
        });
        getContentPane().add(j77, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 30, 30));

        j78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j78.setText("0");
        getContentPane().add(j78, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 30, 30));

        j79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j79.setText("0");
        getContentPane().add(j79, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 30, 30));

        j80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j80.setText("0");
        getContentPane().add(j80, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 30, 30));

        j81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j81.setText("0");
        getContentPane().add(j81, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 30, 30));

        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jButton2.setText("SHOW ANSWER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("SUDOKU SOLVER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j77ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String[][] a=new String[9][9];
        
        a[1-1][1-1]=j1.getText();
        a[1-1][2-1]=j2.getText();
        a[1-1][3-1]=j3.getText();
        a[1-1][4-1]=j4.getText();
        a[1-1][5-1]=j5.getText();
        a[1-1][6-1]=j6.getText();
        a[1-1][7-1]=j7.getText();
        a[1-1][8-1]=j8.getText();
        a[1-1][9-1]=j9.getText();
        a[2-1][1-1]=j10.getText();
        a[2-1][2-1]=j11.getText();
        a[2-1][3-1]=j12.getText();
        a[2-1][4-1]=j13.getText();
        a[2-1][5-1]=j14.getText();
        a[2-1][6-1]=j15.getText();
        a[2-1][7-1]=j16.getText();
        a[2-1][8-1]=j17.getText();
        a[2-1][9-1]=j18.getText();
        a[3-1][1-1]=j19.getText();
        a[3-1][2-1]=j20.getText();
        a[3-1][3-1]=j21.getText();
        a[3-1][4-1]=j22.getText();
        a[3-1][5-1]=j23.getText();
        a[3-1][6-1]=j24.getText();
        a[3-1][7-1]=j25.getText();
        a[3-1][8-1]=j26.getText();
        a[3-1][9-1]=j27.getText();
        a[4-1][1-1]=j28.getText();
        a[4-1][2-1]=j29.getText();
        a[4-1][3-1]=j30.getText();
        a[4-1][4-1]=j31.getText();
        a[4-1][5-1]=j32.getText();
        a[4-1][6-1]=j33.getText();
        a[4-1][7-1]=j34.getText();
        a[4-1][8-1]=j35.getText();
        a[4-1][9-1]=j36.getText();
        a[5-1][1-1]=j37.getText();
        a[5-1][2-1]=j38.getText();
        a[5-1][3-1]=j39.getText();
        a[5-1][4-1]=j40.getText();
        a[5-1][5-1]=j41.getText();
        a[5-1][6-1]=j42.getText();
        a[5-1][7-1]=j43.getText();
        a[5-1][8-1]=j44.getText();
        a[5-1][9-1]=j45.getText();
        a[6-1][1-1]=j46.getText();
        a[6-1][2-1]=j47.getText();
        a[6-1][3-1]=j48.getText();
        a[6-1][4-1]=j49.getText();
        a[6-1][5-1]=j50.getText();
        a[6-1][6-1]=j51.getText();
        a[6-1][7-1]=j52.getText();
        a[6-1][8-1]=j53.getText();
        a[6-1][9-1]=j54.getText();
        a[7-1][1-1]=j55.getText();
        a[7-1][2-1]=j56.getText();
        a[7-1][3-1]=j57.getText();
        a[7-1][4-1]=j58.getText();
        a[7-1][5-1]=j59.getText();
        a[7-1][6-1]=j60.getText();
        a[7-1][7-1]=j61.getText();
        a[7-1][8-1]=j62.getText();
        a[7-1][9-1]=j63.getText();
        a[8-1][1-1]=j64.getText();
        a[8-1][2-1]=j65.getText();
        a[8-1][3-1]=j66.getText();
        a[8-1][4-1]=j67.getText();
        a[8-1][5-1]=j68.getText();
        a[8-1][6-1]=j69.getText();
        a[8-1][7-1]=j70.getText();
        a[8-1][8-1]=j71.getText();
        a[8-1][9-1]=j72.getText();
        a[9-1][1-1]=j73.getText();
        a[9-1][2-1]=j74.getText();
        a[9-1][3-1]=j75.getText();
        a[9-1][4-1]=j76.getText();
        a[9-1][5-1]=j77.getText();
        a[9-1][6-1]=j78.getText();
        a[9-1][7-1]=j79.getText();
        a[9-1][8-1]=j80.getText();
        a[9-1][9-1]=j81.getText();
        
        /*a[1-1][1-1]=Integer.parseInt(j1.getText());
        a[1-1][2-1]=Integer.parseInt(j2.getText());
        a[1-1][3-1]=Integer.parseInt(j3.getText());
        a[1-1][4-1]=Integer.parseInt(j4.getText());
        a[1-1][5-1]=Integer.parseInt(j5.getText());
        a[1-1][6-1]=Integer.parseInt(j6.getText());
        a[1-1][7-1]=Integer.parseInt(j7.getText());
        a[1-1][8-1]=Integer.parseInt(j8.getText());
        a[1-1][9-1]=Integer.parseInt(j9.getText());
        a[2-1][1-1]=Integer.parseInt(j10.getText());
        a[2-1][2-1]=Integer.parseInt(j11.getText());
        a[2-1][3-1]=Integer.parseInt(j12.getText());
        a[2-1][4-1]=Integer.parseInt(j13.getText());
        a[2-1][5-1]=Integer.parseInt(j14.getText());
        a[2-1][6-1]=Integer.parseInt(j15.getText());
        a[2-1][7-1]=Integer.parseInt(j16.getText());
        a[2-1][8-1]=Integer.parseInt(j17.getText());
        a[2-1][9-1]=Integer.parseInt(j18.getText());
        a[3-1][1-1]=Integer.parseInt(j19.getText());
        a[3-1][2-1]=Integer.parseInt(j20.getText());
        a[3-1][3-1]=Integer.parseInt(j21.getText());
        a[3-1][4-1]=Integer.parseInt(j22.getText());
        a[3-1][5-1]=Integer.parseInt(j23.getText());
        a[3-1][6-1]=Integer.parseInt(j24.getText());
        a[3-1][7-1]=Integer.parseInt(j25.getText());
        a[3-1][8-1]=Integer.parseInt(j26.getText());
        a[3-1][9-1]=Integer.parseInt(j27.getText());
        a[4-1][1-1]=Integer.parseInt(j28.getText());
        a[4-1][2-1]=Integer.parseInt(j29.getText());
        a[4-1][3-1]=Integer.parseInt(j30.getText());
        a[4-1][4-1]=Integer.parseInt(j31.getText());
        a[4-1][5-1]=Integer.parseInt(j32.getText());
        a[4-1][6-1]=Integer.parseInt(j33.getText());
        a[4-1][7-1]=Integer.parseInt(j34.getText());
        a[4-1][8-1]=Integer.parseInt(j35.getText());
        a[4-1][9-1]=Integer.parseInt(j36.getText());
        a[5-1][1-1]=Integer.parseInt(j37.getText());
        a[5-1][2-1]=Integer.parseInt(j38.getText());
        a[5-1][3-1]=Integer.parseInt(j39.getText());
        a[5-1][4-1]=Integer.parseInt(j40.getText());
        a[5-1][5-1]=Integer.parseInt(j41.getText());
        a[5-1][6-1]=Integer.parseInt(j42.getText());
        a[5-1][7-1]=Integer.parseInt(j43.getText());
        a[5-1][8-1]=Integer.parseInt(j44.getText());
        a[5-1][9-1]=Integer.parseInt(j45.getText());
        a[6-1][1-1]=Integer.parseInt(j46.getText());
        a[6-1][2-1]=Integer.parseInt(j47.getText());
        a[6-1][3-1]=Integer.parseInt(j48.getText());
        a[6-1][4-1]=Integer.parseInt(j49.getText());
        a[6-1][5-1]=Integer.parseInt(j50.getText());
        a[6-1][6-1]=Integer.parseInt(j51.getText());
        a[6-1][7-1]=Integer.parseInt(j52.getText());
        a[6-1][8-1]=Integer.parseInt(j53.getText());
        a[6-1][9-1]=Integer.parseInt(j54.getText());
        a[7-1][1-1]=Integer.parseInt(j55.getText());
        a[7-1][2-1]=Integer.parseInt(j56.getText());
        a[7-1][3-1]=Integer.parseInt(j57.getText());
        a[7-1][4-1]=Integer.parseInt(j58.getText());
        a[7-1][5-1]=Integer.parseInt(j59.getText());
        a[7-1][6-1]=Integer.parseInt(j60.getText());
        a[7-1][7-1]=Integer.parseInt(j61.getText());
        a[7-1][8-1]=Integer.parseInt(j62.getText());
        a[7-1][9-1]=Integer.parseInt(j63.getText());
        a[8-1][1-1]=Integer.parseInt(j64.getText());
        a[8-1][2-1]=Integer.parseInt(j65.getText());
        a[8-1][3-1]=Integer.parseInt(j66.getText());
        a[8-1][4-1]=Integer.parseInt(j67.getText());
        a[8-1][5-1]=Integer.parseInt(j68.getText());
        a[8-1][6-1]=Integer.parseInt(j69.getText());
        a[8-1][7-1]=Integer.parseInt(j70.getText());
        a[8-1][8-1]=Integer.parseInt(j71.getText());
        a[8-1][9-1]=Integer.parseInt(j72.getText());
        a[9-1][1-1]=Integer.parseInt(j73.getText());
        a[9-1][2-1]=Integer.parseInt(j74.getText());
        a[9-1][3-1]=Integer.parseInt(j75.getText());
        a[9-1][4-1]=Integer.parseInt(j76.getText());
        a[9-1][5-1]=Integer.parseInt(j77.getText());
        a[9-1][6-1]=Integer.parseInt(j78.getText());
        a[9-1][7-1]=Integer.parseInt(j79.getText());
        a[9-1][8-1]=Integer.parseInt(j80.getText());
        a[9-1][9-1]=Integer.parseInt(j81.getText());*/
        int i,j=0,k=1,l=0,m=0;
        for(i=0;i<9;i++)
        {
            for(j=0;j<9;j++)
            {
                if(!a[i][j].equals("0") && !a[i][j].equals("1") && !a[i][j].equals("2") && !a[i][j].equals("3") && !a[i][j].equals("4") && !a[i][j].equals("5") && !a[i][j].equals("6") && !a[i][j].equals("7") && !a[i][j].equals("8") && !a[i][j].equals("9"))
                {
                    k=0;
                    l=i;
                    m=j;
                    break;
                }
                c[i][j]=Integer.parseInt(a[i][j]);
            }
        }
        if(k==1)
            Sudoku.ready(c);
        else
            JOptionPane.showMessageDialog(null,"Enter numbers between 0-9 in index ["+(l+1)+"]["+(m+1)+"]");
        /*ArrayList<JTextField> allEditText = new ArrayList<JTextField>();
        for(int j=1;j<=81;j++)
        {
           allEditText.add((JTextField)("j1"));
        }
        String[] edString = new String[(allEditText.size())];
        for(int i=0; i < allEditText.size(); i++){
               edString[i] = allEditText.get(i).getText().toString();
               allEditText.get(i).setText("hh");
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     
        
        String[][] a=new String[9][9];
        
        a[1-1][1-1]=j1.getText();
        a[1-1][2-1]=j2.getText();
        a[1-1][3-1]=j3.getText();
        a[1-1][4-1]=j4.getText();
        a[1-1][5-1]=j5.getText();
        a[1-1][6-1]=j6.getText();
        a[1-1][7-1]=j7.getText();
        a[1-1][8-1]=j8.getText();
        a[1-1][9-1]=j9.getText();
        a[2-1][1-1]=j10.getText();
        a[2-1][2-1]=j11.getText();
        a[2-1][3-1]=j12.getText();
        a[2-1][4-1]=j13.getText();
        a[2-1][5-1]=j14.getText();
        a[2-1][6-1]=j15.getText();
        a[2-1][7-1]=j16.getText();
        a[2-1][8-1]=j17.getText();
        a[2-1][9-1]=j18.getText();
        a[3-1][1-1]=j19.getText();
        a[3-1][2-1]=j20.getText();
        a[3-1][3-1]=j21.getText();
        a[3-1][4-1]=j22.getText();
        a[3-1][5-1]=j23.getText();
        a[3-1][6-1]=j24.getText();
        a[3-1][7-1]=j25.getText();
        a[3-1][8-1]=j26.getText();
        a[3-1][9-1]=j27.getText();
        a[4-1][1-1]=j28.getText();
        a[4-1][2-1]=j29.getText();
        a[4-1][3-1]=j30.getText();
        a[4-1][4-1]=j31.getText();
        a[4-1][5-1]=j32.getText();
        a[4-1][6-1]=j33.getText();
        a[4-1][7-1]=j34.getText();
        a[4-1][8-1]=j35.getText();
        a[4-1][9-1]=j36.getText();
        a[5-1][1-1]=j37.getText();
        a[5-1][2-1]=j38.getText();
        a[5-1][3-1]=j39.getText();
        a[5-1][4-1]=j40.getText();
        a[5-1][5-1]=j41.getText();
        a[5-1][6-1]=j42.getText();
        a[5-1][7-1]=j43.getText();
        a[5-1][8-1]=j44.getText();
        a[5-1][9-1]=j45.getText();
        a[6-1][1-1]=j46.getText();
        a[6-1][2-1]=j47.getText();
        a[6-1][3-1]=j48.getText();
        a[6-1][4-1]=j49.getText();
        a[6-1][5-1]=j50.getText();
        a[6-1][6-1]=j51.getText();
        a[6-1][7-1]=j52.getText();
        a[6-1][8-1]=j53.getText();
        a[6-1][9-1]=j54.getText();
        a[7-1][1-1]=j55.getText();
        a[7-1][2-1]=j56.getText();
        a[7-1][3-1]=j57.getText();
        a[7-1][4-1]=j58.getText();
        a[7-1][5-1]=j59.getText();
        a[7-1][6-1]=j60.getText();
        a[7-1][7-1]=j61.getText();
        a[7-1][8-1]=j62.getText();
        a[7-1][9-1]=j63.getText();
        a[8-1][1-1]=j64.getText();
        a[8-1][2-1]=j65.getText();
        a[8-1][3-1]=j66.getText();
        a[8-1][4-1]=j67.getText();
        a[8-1][5-1]=j68.getText();
        a[8-1][6-1]=j69.getText();
        a[8-1][7-1]=j70.getText();
        a[8-1][8-1]=j71.getText();
        a[8-1][9-1]=j72.getText();
        a[9-1][1-1]=j73.getText();
        a[9-1][2-1]=j74.getText();
        a[9-1][3-1]=j75.getText();
        a[9-1][4-1]=j76.getText();
        a[9-1][5-1]=j77.getText();
        a[9-1][6-1]=j78.getText();
        a[9-1][7-1]=j79.getText();
        a[9-1][8-1]=j80.getText();
        a[9-1][9-1]=j81.getText();
        
        /*a[1-1][1-1]=Integer.parseInt(j1.getText());
        a[1-1][2-1]=Integer.parseInt(j2.getText());
        a[1-1][3-1]=Integer.parseInt(j3.getText());
        a[1-1][4-1]=Integer.parseInt(j4.getText());
        a[1-1][5-1]=Integer.parseInt(j5.getText());
        a[1-1][6-1]=Integer.parseInt(j6.getText());
        a[1-1][7-1]=Integer.parseInt(j7.getText());
        a[1-1][8-1]=Integer.parseInt(j8.getText());
        a[1-1][9-1]=Integer.parseInt(j9.getText());
        a[2-1][1-1]=Integer.parseInt(j10.getText());
        a[2-1][2-1]=Integer.parseInt(j11.getText());
        a[2-1][3-1]=Integer.parseInt(j12.getText());
        a[2-1][4-1]=Integer.parseInt(j13.getText());
        a[2-1][5-1]=Integer.parseInt(j14.getText());
        a[2-1][6-1]=Integer.parseInt(j15.getText());
        a[2-1][7-1]=Integer.parseInt(j16.getText());
        a[2-1][8-1]=Integer.parseInt(j17.getText());
        a[2-1][9-1]=Integer.parseInt(j18.getText());
        a[3-1][1-1]=Integer.parseInt(j19.getText());
        a[3-1][2-1]=Integer.parseInt(j20.getText());
        a[3-1][3-1]=Integer.parseInt(j21.getText());
        a[3-1][4-1]=Integer.parseInt(j22.getText());
        a[3-1][5-1]=Integer.parseInt(j23.getText());
        a[3-1][6-1]=Integer.parseInt(j24.getText());
        a[3-1][7-1]=Integer.parseInt(j25.getText());
        a[3-1][8-1]=Integer.parseInt(j26.getText());
        a[3-1][9-1]=Integer.parseInt(j27.getText());
        a[4-1][1-1]=Integer.parseInt(j28.getText());
        a[4-1][2-1]=Integer.parseInt(j29.getText());
        a[4-1][3-1]=Integer.parseInt(j30.getText());
        a[4-1][4-1]=Integer.parseInt(j31.getText());
        a[4-1][5-1]=Integer.parseInt(j32.getText());
        a[4-1][6-1]=Integer.parseInt(j33.getText());
        a[4-1][7-1]=Integer.parseInt(j34.getText());
        a[4-1][8-1]=Integer.parseInt(j35.getText());
        a[4-1][9-1]=Integer.parseInt(j36.getText());
        a[5-1][1-1]=Integer.parseInt(j37.getText());
        a[5-1][2-1]=Integer.parseInt(j38.getText());
        a[5-1][3-1]=Integer.parseInt(j39.getText());
        a[5-1][4-1]=Integer.parseInt(j40.getText());
        a[5-1][5-1]=Integer.parseInt(j41.getText());
        a[5-1][6-1]=Integer.parseInt(j42.getText());
        a[5-1][7-1]=Integer.parseInt(j43.getText());
        a[5-1][8-1]=Integer.parseInt(j44.getText());
        a[5-1][9-1]=Integer.parseInt(j45.getText());
        a[6-1][1-1]=Integer.parseInt(j46.getText());
        a[6-1][2-1]=Integer.parseInt(j47.getText());
        a[6-1][3-1]=Integer.parseInt(j48.getText());
        a[6-1][4-1]=Integer.parseInt(j49.getText());
        a[6-1][5-1]=Integer.parseInt(j50.getText());
        a[6-1][6-1]=Integer.parseInt(j51.getText());
        a[6-1][7-1]=Integer.parseInt(j52.getText());
        a[6-1][8-1]=Integer.parseInt(j53.getText());
        a[6-1][9-1]=Integer.parseInt(j54.getText());
        a[7-1][1-1]=Integer.parseInt(j55.getText());
        a[7-1][2-1]=Integer.parseInt(j56.getText());
        a[7-1][3-1]=Integer.parseInt(j57.getText());
        a[7-1][4-1]=Integer.parseInt(j58.getText());
        a[7-1][5-1]=Integer.parseInt(j59.getText());
        a[7-1][6-1]=Integer.parseInt(j60.getText());
        a[7-1][7-1]=Integer.parseInt(j61.getText());
        a[7-1][8-1]=Integer.parseInt(j62.getText());
        a[7-1][9-1]=Integer.parseInt(j63.getText());
        a[8-1][1-1]=Integer.parseInt(j64.getText());
        a[8-1][2-1]=Integer.parseInt(j65.getText());
        a[8-1][3-1]=Integer.parseInt(j66.getText());
        a[8-1][4-1]=Integer.parseInt(j67.getText());
        a[8-1][5-1]=Integer.parseInt(j68.getText());
        a[8-1][6-1]=Integer.parseInt(j69.getText());
        a[8-1][7-1]=Integer.parseInt(j70.getText());
        a[8-1][8-1]=Integer.parseInt(j71.getText());
        a[8-1][9-1]=Integer.parseInt(j72.getText());
        a[9-1][1-1]=Integer.parseInt(j73.getText());
        a[9-1][2-1]=Integer.parseInt(j74.getText());
        a[9-1][3-1]=Integer.parseInt(j75.getText());
        a[9-1][4-1]=Integer.parseInt(j76.getText());
        a[9-1][5-1]=Integer.parseInt(j77.getText());
        a[9-1][6-1]=Integer.parseInt(j78.getText());
        a[9-1][7-1]=Integer.parseInt(j79.getText());
        a[9-1][8-1]=Integer.parseInt(j80.getText());
        a[9-1][9-1]=Integer.parseInt(j81.getText());*/
        int i,j=0,k=1,l=0,m=0;
        for(i=0;i<9;i++)
        {
            for(j=0;j<9;j++)
            {
                if(!a[i][j].equals("0") && !a[i][j].equals("1") && !a[i][j].equals("2") && !a[i][j].equals("3") && !a[i][j].equals("4") && !a[i][j].equals("5") && !a[i][j].equals("6") && !a[i][j].equals("7") && !a[i][j].equals("8") && !a[i][j].equals("9"))
                {
                    k=0;
                    l=i;
                    m=j;
                    break;
                }
                c[i][j]=Integer.parseInt(a[i][j]);
            }
        }
        if(k==1)
        {
            int f;
            f=Sudoku.ready2(c);
            if(f==1)
            {
                Answer A=new Answer(c);
                A.setExtendedState(Answer.MAXIMIZED_BOTH);
                A.setVisible(true);
            }
        }
        else
            JOptionPane.showMessageDialog(null,"Enter numbers between 0-9 in index ["+(l+1)+"]["+(m+1)+"]");
        //Sudoku.ready2(a);
        //Answer A=new Answer(a);
        //A.setExtendedState(Answer.MAXIMIZED_BOTH);
        //A.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Start s=new Start();
                s.setExtendedState(Start.MAXIMIZED_BOTH);
                s.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j19;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j25;
    private javax.swing.JTextField j26;
    private javax.swing.JTextField j27;
    private javax.swing.JTextField j28;
    private javax.swing.JTextField j29;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j30;
    private javax.swing.JTextField j31;
    private javax.swing.JTextField j32;
    private javax.swing.JTextField j33;
    private javax.swing.JTextField j34;
    private javax.swing.JTextField j35;
    private javax.swing.JTextField j36;
    private javax.swing.JTextField j37;
    private javax.swing.JTextField j38;
    private javax.swing.JTextField j39;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j40;
    private javax.swing.JTextField j41;
    private javax.swing.JTextField j42;
    private javax.swing.JTextField j43;
    private javax.swing.JTextField j44;
    private javax.swing.JTextField j45;
    private javax.swing.JTextField j46;
    private javax.swing.JTextField j47;
    private javax.swing.JTextField j48;
    private javax.swing.JTextField j49;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j50;
    private javax.swing.JTextField j51;
    private javax.swing.JTextField j52;
    private javax.swing.JTextField j53;
    private javax.swing.JTextField j54;
    private javax.swing.JTextField j55;
    private javax.swing.JTextField j56;
    private javax.swing.JTextField j57;
    private javax.swing.JTextField j58;
    private javax.swing.JTextField j59;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j60;
    private javax.swing.JTextField j61;
    private javax.swing.JTextField j62;
    private javax.swing.JTextField j63;
    private javax.swing.JTextField j64;
    private javax.swing.JTextField j65;
    private javax.swing.JTextField j66;
    private javax.swing.JTextField j67;
    private javax.swing.JTextField j68;
    private javax.swing.JTextField j69;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j70;
    private javax.swing.JTextField j71;
    private javax.swing.JTextField j72;
    private javax.swing.JTextField j73;
    private javax.swing.JTextField j74;
    private javax.swing.JTextField j75;
    private javax.swing.JTextField j76;
    private javax.swing.JTextField j77;
    private javax.swing.JTextField j78;
    private javax.swing.JTextField j79;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j80;
    private javax.swing.JTextField j81;
    private javax.swing.JTextField j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
